import subprocess
from string import Template

import pytest
from pathlib import Path

from app import models, schemas
from app.db import get_db
from app.services import codex_execution_service, step_execution_service, task_service
from test_phase1_flow import approve_plan, create_run, create_task, generate_plan, submit_run


def test_background_step_execution_auto_approves_and_unlocks_next_step(client, monkeypatch):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step, second_step = detail["steps"]

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        assert task_model.id == task["id"]
        assert step_model.id == first_step["id"]
        assert run_input == {"note": "attempt"}
        assert previous_steps == []
        return {"summary": "LLM finished step one", "details": "Generated by test"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    run = create_run(client, task["id"], first_step["id"], "agent")
    assert run["status"] == "running"

    runs = client.get(f"/tasks/{task['id']}/steps/{first_step['id']}/runs").json()
    completed_run = runs[0]
    assert completed_run["status"] == "accepted"
    assert completed_run["output"]["summary"] == "LLM finished step one"

    detail = client.get(f"/tasks/{task['id']}").json()
    approved_step = next(step for step in detail["steps"] if step["id"] == first_step["id"])
    assert approved_step["status"] == "approved"
    assert approved_step["approved_run_id"] == run["id"]
    assert detail["task"]["status"] == "planned"
    assert detail["current_pointer"] == {
        "task_id": task["id"],
        "step_id": second_step["id"],
        "run_id": None,
        "capability_invocation_id": None,
    }
    start_actions = [action for action in detail["next_actions"] if action["action_type"] == "start_step_run"]
    assert len(start_actions) == 1
    assert start_actions[0]["target"] == {"task_id": task["id"], "step_id": second_step["id"]}


def test_background_step_execution_failure_marks_run_step_and_task_failed(client, monkeypatch):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]

    def fake_execute_step(*args, **kwargs):
        raise RuntimeError("executor failed")

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    run = create_run(client, task["id"], step["id"], "agent")
    assert run["status"] == "running"

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    failed_run = runs[0]
    assert failed_run["status"] == "failed"
    assert "executor failed" in failed_run["error"]

    detail = client.get(f"/tasks/{task['id']}").json()
    failed_step = next(item for item in detail["steps"] if item["id"] == step["id"])
    assert failed_step["status"] == "failed"
    assert detail["task"]["status"] == "failed"


def test_auto_run_executes_all_remaining_steps(client, monkeypatch):
    task = create_task(client)
    generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    seen_steps = []

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        seen_steps.append(step_model.id)
        assert run_input == {"instruction": "auto", "auto_run": True}
        return {"summary": f"completed {step_model.title}", "details": "Generated by test"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(
        f"/tasks/{task['id']}/auto-run",
        json={"executor_type": "agent", "input": {"instruction": "auto"}},
    )
    assert response.status_code == 200, response.text
    payload = response.json()
    assert payload["started"] is True

    detail = client.get(f"/tasks/{task['id']}").json()
    assert detail["task"]["status"] == "completed"
    assert [step["status"] for step in detail["steps"]] == ["approved", "approved"]
    assert seen_steps == [step["id"] for step in detail["steps"]]
    for step in detail["steps"]:
        runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
        assert len(runs) == 1
        assert runs[0]["status"] == "accepted"


def test_auto_run_from_step_runs_branch_on_completed_task(client, monkeypatch):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step, second_step = detail["steps"]

    for step in [first_step, second_step]:
        run = create_run(client, task["id"], step["id"], "human")
        submit_run(client, task["id"], step["id"], run["id"])
        response = client.post(f"/tasks/{task['id']}/steps/{step['id']}/runs/{run['id']}/review", json={"decision": "approved"})
        assert response.status_code == 200, response.text

    detail = client.get(f"/tasks/{task['id']}").json()
    assert detail["task"]["status"] == "completed"
    branch_response = client.post(
        f"/tasks/{task['id']}/steps/{first_step['id']}/rerun",
        json={"executor_type": "agent", "input": {}, "change_request": "Run branch from here"},
    )
    assert branch_response.status_code == 200, branch_response.text
    branch_step_id = branch_response.json()["forked_step_id"]
    detail = client.get(f"/tasks/{task['id']}").json()
    branch_step = next(step for step in detail["steps"] if step["id"] == branch_step_id)
    branch_successor_id = branch_step["next_step_ids"][0]
    seen_steps = []

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        seen_steps.append(step_model.id)
        assert run_input == {"instruction": "branch", "auto_run": True, "auto_run_start_step_id": branch_step_id}
        return {"summary": f"completed {step_model.title}", "details": "Generated by test"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(
        f"/tasks/{task['id']}/steps/{branch_step_id}/auto-run",
        json={"executor_type": "agent", "input": {"instruction": "branch"}},
    )
    assert response.status_code == 200, response.text
    assert response.json()["started"] is True

    detail = client.get(f"/tasks/{task['id']}").json()
    branch_step = next(step for step in detail["steps"] if step["id"] == branch_step_id)
    branch_successor = next(step for step in detail["steps"] if step["id"] == branch_successor_id)
    assert branch_step["status"] == "approved"
    assert branch_successor["status"] == "approved"
    assert seen_steps == [branch_step_id, branch_successor_id]


def test_auto_run_stops_on_step_failure(client, monkeypatch):
    task = create_task(client)
    generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    calls = 0

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        nonlocal calls
        calls += 1
        if calls == 2:
            raise RuntimeError("second step failed")
        return {"summary": "first complete", "details": "Generated by test"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(f"/tasks/{task['id']}/auto-run", json={"executor_type": "agent", "input": {}})
    assert response.status_code == 200, response.text

    detail = client.get(f"/tasks/{task['id']}").json()
    assert detail["task"]["status"] == "failed"
    assert [step["status"] for step in detail["steps"]] == ["approved", "failed"]
    first_step, second_step = detail["steps"]
    first_runs = client.get(f"/tasks/{task['id']}/steps/{first_step['id']}/runs").json()
    second_runs = client.get(f"/tasks/{task['id']}/steps/{second_step['id']}/runs").json()
    assert first_runs[0]["status"] == "accepted"
    assert second_runs[0]["status"] == "failed"
    assert "second step failed" in second_runs[0]["error"]


def test_auto_run_does_not_duplicate_while_running(client):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step = detail["steps"][0]
    create_run(client, task["id"], first_step["id"], "human")

    response = client.post(f"/tasks/{task['id']}/auto-run", json={"executor_type": "agent", "input": {}})
    assert response.status_code == 200, response.text
    assert response.json()["started"] is False

    runs = client.get(f"/tasks/{task['id']}/steps/{first_step['id']}/runs").json()
    assert len(runs) == 1
    assert runs[0]["executor_type"] == "human"


def test_codex_prompt_uses_template_loader(monkeypatch):
    monkeypatch.setattr(
        codex_execution_service,
        "load_codex_step_prompt_template",
        lambda: Template("CUSTOM $task_title $step_title $run_input_json $previous_steps_context"),
    )
    task = models.Task(id=1, title="Template task", goal="Use template", constraints=None)
    step = models.Step(id=2, task_id=1, title="Template step", objective="Render prompt", step_order=3)
    run = models.StepRun(id=4, task_id=1, step_id=2, attempt_number=1)

    prompt = codex_execution_service.build_prompt(
        task,
        step,
        run,
        {"note": "ok"},
        [{"step_order": 1, "title": "Previous", "summary": "Done"}],
    )

    assert prompt.startswith("CUSTOM Template task Template step")
    assert '{"note": "ok"}' in prompt
    assert "Completed previous steps count: 1" in prompt


def test_codex_step_prompt_directs_xcode_artifacts_into_project_directory():
    task = models.Task(id=1, title="Mac app", goal="Build app", constraints=None)
    step = models.Step(id=2, task_id=1, title="Run Xcode tests", objective="Verify timer", step_order=3)
    run = models.StepRun(id=4, task_id=1, step_id=2, attempt_number=1)

    prompt = codex_execution_service.build_prompt(task, step, run, {}, [])

    assert '-derivedDataPath "$LONG_AGENT_XCODE_DERIVED_DATA_PATH"' in prompt
    assert '-resultBundlePath "$LONG_AGENT_XCODE_RESULT_BUNDLE_PATH"' in prompt
    assert "Do not read or write ~/Library/Developer/Xcode/DerivedData" in prompt


def test_codex_prompt_includes_previous_hook_summary(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(codex_execution_service, "start_task_codex_keepalive", lambda task_id, project_path: None)
    sent_prompts = []

    def fake_start_codex_tmux(task_model, step_model, run_model, run_input, previous_step_summaries=None):
        sent_prompts.append(codex_execution_service.build_prompt(task_model, step_model, run_model, run_input, previous_step_summaries))
        return {"tmux_session": "longagent-test", "workdir": str(tmp_path)}

    monkeypatch.setattr(codex_execution_service, "start_codex_tmux", fake_start_codex_tmux)
    task_response = client.post(
        "/tasks",
        json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)},
    )
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step, second_step = detail["steps"]
    first_run = create_run(client, task["id"], first_step["id"], "agent")
    token = codex_execution_service.make_callback_token(task["id"], first_step["id"], first_run["id"], first_run["attempt_number"])
    response = client.post(
        f"/internal/codex/runs/{first_run['id']}/callback",
        headers={"Authorization": f"Bearer {token}"},
        json={
            "task_id": task["id"],
            "step_id": first_step["id"],
            "run_id": first_run["id"],
            "attempt_number": first_run["attempt_number"],
            "status": "completed",
            "summary": "raw hook summary",
            "details": {"hook_payload": '{"last_assistant_message":"Created multiplication_table.py only."}'},
        },
    )
    assert response.status_code == 200, response.text

    create_run(client, task["id"], second_step["id"], "agent")

    assert "Created multiplication_table.py only." in sent_prompts[-1]
    assert "Completed previous steps and their approved results" in sent_prompts[-1]
    assert "Completed previous steps count: 1" in sent_prompts[-1]
    assert "Completed Step 1: Step one" in sent_prompts[-1]
    assert f"Step {second_step['step_order']}: {second_step['title']}" in sent_prompts[-1]


def test_codex_task_launches_tmux_with_environment(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(
        codex_execution_service,
        "start_task_codex_keepalive",
        lambda task_id, project_path: codex_execution_service.initialize_task_codex_session(task_id, project_path),
    )
    launched = {}

    def fake_run(args, check):
        launched.setdefault("commands", []).append(args)
        class Result:
            returncode = 1 if args[:3] == ["tmux", "has-session", "-t"] else 0
        return Result()

    monkeypatch.setattr(codex_execution_service.subprocess, "run", fake_run)
    task_response = client.post(
        "/tasks",
        json={
            "title": "Codex task",
            "goal": "Implement project code",
            "project_path": str(tmp_path),
            "executor_mode": "codex",
        },
    )
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]

    run = create_run(client, task["id"], step["id"], "agent")

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert runs[0]["status"] == "running"
    assert runs[0]["executor_type"] == "codex"
    new_session = next(args for args in launched["commands"] if args[:2] == ["tmux", "new-session"])
    session_command = new_session[-1]
    assert "CODEX_STOP_SCRIPT=" in session_command
    assert "-c 'env.CODEX_STOP_SCRIPT=" in session_command
    assert "LONG_AGENT_CALLBACK_URL=" in session_command
    assert "-c 'env.LONG_AGENT_CALLBACK_URL=" in session_command
    assert "LONG_AGENT_TASK_ID=" in session_command
    assert "-c 'env.LONG_AGENT_TASK_ID=" in session_command
    assert "LONG_AGENT_CALLBACK_TOKEN=" in session_command
    assert "-c 'env.LONG_AGENT_CALLBACK_TOKEN=" in session_command
    assert "LONG_AGENT_XCODE_DERIVED_DATA_PATH=" in session_command
    assert "-c 'env.LONG_AGENT_XCODE_DERIVED_DATA_PATH=" in session_command
    assert "LONG_AGENT_XCODE_RESULT_BUNDLE_PATH=" in session_command
    assert "-c 'env.LONG_AGENT_XCODE_RESULT_BUNDLE_PATH=" in session_command
    assert "--enable hooks" in session_command
    assert f"--cd {tmp_path}" in session_command
    send_keys = [args for args in launched["commands"] if args[:2] == ["tmux", "send-keys"]]
    expected_session = f"longagent-t{task['id']}"
    assert send_keys[0][:6] == ["tmux", "send-keys", "-t", expected_session, "-l", "--"]
    assert "Step 1: Step one" in send_keys[0][-1]
    assert "Goal:" not in send_keys[0][-1]
    assert "Do not implement later steps" in send_keys[0][-1]
    assert send_keys[1] == ["tmux", "send-keys", "-t", expected_session, "Enter"]
    assert run["status"] == "running"


def test_codex_session_reinitialize_fails_stale_running_run(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(codex_execution_service, "start_task_codex_keepalive", lambda task_id, project_path: None)

    def fake_run(args, check, **_kwargs):
        class Result:
            returncode = 1 if args[:3] == ["tmux", "has-session", "-t"] else 0
            stdout = "OpenAI Codex\n›"
        return Result()

    monkeypatch.setattr(codex_execution_service.subprocess, "run", fake_run)
    task_response = client.post(
        "/tasks",
        json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)},
    )
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]

    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        task_model = task_service.get_task_or_404(db, task["id"])
        step_model = db.get(models.Step, step["id"])
        task_model.status = "in_progress"
        step_model.status = "running"
        run = models.StepRun(
            task_id=task["id"],
            step_id=step["id"],
            attempt_number=1,
            executor_type="codex",
            status="running",
            input="{}",
            output=task_service.encode_json({"executor": "codex", "status": "launched", "tmux_session": "longagent-test"}),
            started_at=models.utcnow(),
        )
        db.add(run)
        db.commit()
    finally:
        db.close()

    codex_execution_service.initialize_task_codex_session(task["id"], str(tmp_path))

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert runs[0]["status"] == "failed"
    assert runs[0]["error"] == "Codex tmux session was reinitialized"
    detail = client.get(f"/tasks/{task['id']}").json()
    refreshed_step = next(item for item in detail["steps"] if item["id"] == step["id"])
    assert refreshed_step["status"] == "failed"
    assert detail["task"]["status"] == "failed"



def test_codex_task_restarts_tmux_when_send_enter_fails(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(
        codex_execution_service,
        "start_task_codex_keepalive",
        lambda task_id, project_path: codex_execution_service.initialize_task_codex_session(task_id, project_path),
    )
    calls = []
    enter_failures = {"remaining": 1}

    def fake_run(args, check, **_kwargs):
        calls.append(args)
        if args[:3] == ["tmux", "has-session", "-t"]:
            class Result:
                returncode = 1
            return Result()
        if args[:2] == ["tmux", "send-keys"] and args[-1] == "Enter" and enter_failures["remaining"]:
            enter_failures["remaining"] -= 1
            raise subprocess.CalledProcessError(1, args)
        class Result:
            returncode = 0
            stdout = "OpenAI Codex\n›"
        return Result()

    monkeypatch.setattr(codex_execution_service.subprocess, "run", fake_run)
    task_response = client.post(
        "/tasks",
        json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)},
    )
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]

    create_run(client, task["id"], step["id"], "agent")

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert runs[0]["status"] == "running"
    assert [args[:3] for args in calls].count(["tmux", "kill-session", "-t"]) == 1
    assert len([args for args in calls if args[:2] == ["tmux", "new-session"]]) >= 2
    assert len([args for args in calls if args[:2] == ["tmux", "send-keys"] and args[-1] == "Enter"]) == 2


def test_codex_callback_completes_run(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(
        codex_execution_service,
        "start_task_codex_keepalive",
        lambda task_id, project_path: codex_execution_service.initialize_task_codex_session(task_id, project_path),
    )
    monkeypatch.setattr(codex_execution_service.subprocess, "run", lambda args, check: type("Result", (), {"returncode": 1 if args[:3] == ["tmux", "has-session", "-t"] else 0})())
    task_response = client.post("/tasks", json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)})
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]

    run = create_run(client, task["id"], step["id"], "agent")

    token = codex_execution_service.make_callback_token(task["id"], step["id"], run["id"], run["attempt_number"])
    response = client.post(
        f"/internal/codex/runs/{run['id']}/callback",
        headers={"Authorization": f"Bearer {token}"},
        json={
            "task_id": task["id"],
            "step_id": step["id"],
            "run_id": run["id"],
            "attempt_number": run["attempt_number"],
            "status": "completed",
            "summary": "Changed files and finished the step",
        },
    )
    assert response.status_code == 200, response.text
    assert response.json()["accepted"] is True

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert runs[0]["status"] == "accepted"


def test_codex_callback_auto_run_resumes_from_completed_step_successor(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(codex_execution_service, "start_task_codex_keepalive", lambda task_id, project_path: None)
    launched_steps = []

    def fake_start_codex_tmux(task_model, step_model, run_model, run_input, previous_step_summaries=None):
        launched_steps.append(step_model.id)
        return {"tmux_session": "longagent-test", "workdir": str(tmp_path)}

    monkeypatch.setattr(codex_execution_service, "start_codex_tmux", fake_start_codex_tmux)
    task_response = client.post(
        "/tasks",
        json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)},
    )
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step, second_step = detail["steps"]
    for step in [first_step, second_step]:
        run = create_run(client, task["id"], step["id"], "human")
        submit_run(client, task["id"], step["id"], run["id"])
        client.post(f"/tasks/{task['id']}/steps/{step['id']}/runs/{run['id']}/review", json={"decision": "approved"})

    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        branch_root = models.Step(
            task_id=task["id"],
            title="Branch UI",
            objective="Branch UI",
            status="pending",
            position=3,
            step_order=3,
            depends_on_step_ids=[],
            is_active=True,
            is_dynamic=True,
            is_fork=True,
            forked_from_step_id=first_step["id"],
            clone_batch_id="callback-branch",
            branch_status="active",
        )
        branch_child = models.Step(
            task_id=task["id"],
            title="Branch logic",
            objective="Branch logic",
            status="pending",
            position=4,
            step_order=4,
            depends_on_step_ids=[],
            is_active=True,
            is_dynamic=True,
            is_fork=True,
            forked_from_step_id=second_step["id"],
            cloned_from_step_id=second_step["id"],
            clone_batch_id="callback-branch",
            branch_status="active",
        )
        db.add_all([branch_root, branch_child])
        db.flush()
        task_service.link_steps(branch_root, branch_child)
        db.commit()
        branch_root_id = branch_root.id
        branch_child_id = branch_child.id
    finally:
        db.close()

    root_run_response = client.post(
        f"/tasks/{task['id']}/steps/{branch_root_id}/runs",
        json={"executor_type": "agent", "input": {"instruction": "branch", "auto_run": True}},
    )
    assert root_run_response.status_code == 200, root_run_response.text
    root_run = root_run_response.json()
    assert launched_steps == [branch_root_id]

    token = codex_execution_service.make_callback_token(task["id"], branch_root_id, root_run["id"], root_run["attempt_number"])
    response = client.post(
        f"/internal/codex/runs/{root_run['id']}/callback",
        headers={"Authorization": f"Bearer {token}"},
        json={
            "task_id": task["id"],
            "step_id": branch_root_id,
            "run_id": root_run["id"],
            "attempt_number": root_run["attempt_number"],
            "status": "completed",
            "summary": "Branch root complete",
        },
    )
    assert response.status_code == 200, response.text
    assert response.json()["resumed"] is True
    assert launched_steps == [branch_root_id, branch_child_id]
    child_runs = client.get(f"/tasks/{task['id']}/steps/{branch_child_id}/runs").json()
    assert len(child_runs) == 1
    assert child_runs[0]["status"] == "running"
    assert child_runs[0]["input"] == {"instruction": "branch", "auto_run": True}


def test_public_retry_reruns_same_step_without_creating_branch(client):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]
    first_run = create_run(client, task["id"], step["id"], "human")
    client.post(f"/tasks/{task['id']}/steps/{step['id']}/runs/{first_run['id']}/submit", json={"output": {"summary": "first done"}})
    client.post(f"/tasks/{task['id']}/steps/{step['id']}/runs/{first_run['id']}/review", json={"decision": "approved"})

    response = client.post(
        f"/tasks/{task['id']}/steps/{step['id']}/retry",
        json={"executor_type": "human", "input": {"instruction": "same step rerun"}},
    )

    assert response.status_code == 200, response.text
    retry_run = response.json()
    assert retry_run["step_id"] == step["id"]
    assert retry_run["attempt_number"] == 2
    assert retry_run["status"] == "running"

    detail = client.get(f"/tasks/{task['id']}").json()
    steps = detail["steps"]
    retried_step = next(item for item in steps if item["id"] == step["id"])
    assert len(steps) == 2
    assert retried_step["status"] == "running"
    assert retried_step["approved_run_id"] is None
    assert retried_step["comparison_group_id"] is None
    assert retried_step["is_fork"] is False

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert [item["attempt_number"] for item in runs] == [1, 2]
    timeline = client.get(f"/tasks/{task['id']}/timeline").json()
    event_types = [event["event_type"] for event in timeline]
    assert "step_rerun_created" in event_types
    assert "step_rerun_branch_created" not in event_types
    assert "step_branch_cloned" not in event_types



def test_public_agent_retry_auto_runs_downstream_steps(client, monkeypatch):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step, second_step = detail["steps"]
    first_run = create_run(client, task["id"], first_step["id"], "human")
    client.post(f"/tasks/{task['id']}/steps/{first_step['id']}/runs/{first_run['id']}/submit", json={"output": {"summary": "first done"}})
    client.post(f"/tasks/{task['id']}/steps/{first_step['id']}/runs/{first_run['id']}/review", json={"decision": "approved"})
    second_run = create_run(client, task["id"], second_step["id"], "human")
    client.post(f"/tasks/{task['id']}/steps/{second_step['id']}/runs/{second_run['id']}/submit", json={"output": {"summary": "second done"}})
    client.post(f"/tasks/{task['id']}/steps/{second_step['id']}/runs/{second_run['id']}/review", json={"decision": "approved"})

    executed = []

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        executed.append(step_model.id)
        assert run_input["auto_run"] is True
        return {"summary": f"reran {step_model.id}"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(
        f"/tasks/{task['id']}/steps/{first_step['id']}/retry",
        json={"executor_type": "agent", "input": {"instruction": "rerun from here"}},
    )

    assert response.status_code == 200, response.text
    assert executed == [first_step["id"], second_step["id"]]
    first_runs = client.get(f"/tasks/{task['id']}/steps/{first_step['id']}/runs").json()
    second_runs = client.get(f"/tasks/{task['id']}/steps/{second_step['id']}/runs").json()
    assert [run["attempt_number"] for run in first_runs] == [1, 2]
    assert [run["attempt_number"] for run in second_runs] == [1, 2]
    expected_input = {"instruction": "rerun from here", "auto_run": True, "auto_run_start_step_id": first_step["id"]}
    assert first_runs[-1]["input"] == expected_input
    assert second_runs[-1]["input"] == expected_input
    assert first_runs[-1]["status"] == "accepted"
    assert second_runs[-1]["status"] == "accepted"



def test_branch_retry_scope_follows_source_lineage(client):
    task = create_task(client)
    task_id = task["id"]
    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        main_ui = models.Step(task_id=task_id, title="Main UI", objective="UI", status="approved", position=1, step_order=1, depends_on_step_ids=[], is_active=True, is_dynamic=False, is_fork=False)
        main_logic = models.Step(task_id=task_id, title="Main logic", objective="Logic", status="approved", position=2, step_order=2, depends_on_step_ids=[], is_active=True, is_dynamic=False, is_fork=False)
        main_sound = models.Step(task_id=task_id, title="Main sound", objective="Sound", status="approved", position=3, step_order=3, depends_on_step_ids=[], is_active=True, is_dynamic=False, is_fork=False)
        main_package = models.Step(task_id=task_id, title="Main package", objective="Package", status="approved", position=4, step_order=4, depends_on_step_ids=[], is_active=True, is_dynamic=False, is_fork=False)
        db.add_all([main_ui, main_logic, main_sound, main_package])
        db.flush()

        source_batch = "source-branch"
        source_ui = models.Step(task_id=task_id, title="Source UI", objective="UI", status="approved", position=5, step_order=5, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_ui.id, clone_batch_id=source_batch, branch_status="active")
        source_logic = models.Step(task_id=task_id, title="Source logic", objective="Logic", status="approved", position=6, step_order=6, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_logic.id, cloned_from_step_id=main_logic.id, clone_batch_id=source_batch, branch_status="active")
        source_sound = models.Step(task_id=task_id, title="Source sound", objective="Sound", status="approved", position=7, step_order=7, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_sound.id, cloned_from_step_id=main_sound.id, clone_batch_id=source_batch, branch_status="active")
        source_package = models.Step(task_id=task_id, title="Source package", objective="Package", status="approved", position=8, step_order=8, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_package.id, cloned_from_step_id=main_package.id, clone_batch_id=source_batch, branch_status="active")
        db.add_all([source_ui, source_logic, source_sound, source_package])
        db.flush()

        nested_batch = "nested-branch"
        nested_ui = models.Step(task_id=task_id, title="Nested UI", objective="UI", status="approved", position=9, step_order=9, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=source_ui.id, clone_batch_id=nested_batch, branch_status="active")
        wrong_logic = models.Step(task_id=task_id, title="Wrong logic", objective="Logic", status="approved", position=10, step_order=10, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_logic.id, cloned_from_step_id=main_logic.id, clone_batch_id=nested_batch, branch_status="active")
        wrong_sound = models.Step(task_id=task_id, title="Wrong sound", objective="Sound", status="approved", position=11, step_order=11, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_sound.id, cloned_from_step_id=main_sound.id, clone_batch_id=nested_batch, branch_status="active")
        wrong_package = models.Step(task_id=task_id, title="Wrong package", objective="Package", status="approved", position=12, step_order=12, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=main_package.id, cloned_from_step_id=main_package.id, clone_batch_id=nested_batch, branch_status="active")
        expected_logic = models.Step(task_id=task_id, title="Expected logic", objective="Logic", status="approved", position=13, step_order=13, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=source_logic.id, cloned_from_step_id=source_logic.id, clone_batch_id=nested_batch, branch_status="active")
        expected_sound = models.Step(task_id=task_id, title="Expected sound", objective="Sound", status="approved", position=14, step_order=14, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=source_sound.id, cloned_from_step_id=source_sound.id, clone_batch_id=nested_batch, branch_status="active")
        expected_package = models.Step(task_id=task_id, title="Expected package", objective="Package", status="approved", position=15, step_order=15, depends_on_step_ids=[], is_active=True, is_dynamic=True, is_fork=True, forked_from_step_id=source_package.id, cloned_from_step_id=source_package.id, clone_batch_id=nested_batch, branch_status="active")
        db.add_all([nested_ui, wrong_logic, wrong_sound, wrong_package, expected_logic, expected_sound, expected_package])
        db.commit()

        task_service.ensure_step_graph_backfilled(db, task_id)
        continuation_ids = [step.id for step in task_service.graph_continuation_steps(db, task_id, nested_ui)]
        assert [nested_ui.id, *continuation_ids] == [nested_ui.id, expected_logic.id, expected_sound.id, expected_package.id]
    finally:
        db.close()


def test_step_graph_backfill_repairs_missing_reverse_edges(client):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    first_step, second_step = detail["steps"]
    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        first_model = db.get(models.Step, first_step["id"])
        second_model = db.get(models.Step, second_step["id"])
        first_model.next_step_ids = [second_model.id]
        second_model.previous_step_ids = []
        second_model.next_step_ids = []
        db.commit()

        task_service.ensure_step_graph_backfilled(db, task["id"])
        assert second_model.previous_step_ids == [first_model.id]
    finally:
        db.close()


def test_auto_run_advances_through_current_step_successors(client, monkeypatch):
    task = create_task(client)
    detail = client.post(
        f"/tasks/{task['id']}/generate-plan",
        json={
            "steps": [
                {"title": "Root", "objective": "Root"},
                {"title": "Main next", "objective": "Main"},
                {"title": "Sibling next", "objective": "Sibling"},
            ]
        },
    ).json()
    approve_plan(client, task["id"])
    root, main_next, sibling_next = detail["steps"]
    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        root_model = db.get(models.Step, root["id"])
        main_model = db.get(models.Step, main_next["id"])
        sibling_model = db.get(models.Step, sibling_next["id"])
        root_model.next_step_ids = [main_model.id]
        main_model.previous_step_ids = [root_model.id]
        main_model.next_step_ids = []
        sibling_model.previous_step_ids = []
        sibling_model.next_step_ids = []
        db.commit()
    finally:
        db.close()
    executed = []

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        executed.append(step_model.id)
        return {"summary": f"completed {step_model.id}"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(
        f"/tasks/{task['id']}/auto-run",
        json={"executor_type": "agent", "input": {}},
    )

    assert response.status_code == 200, response.text
    assert executed == [root["id"], main_next["id"]]
    detail = client.get(f"/tasks/{task['id']}").json()
    statuses = {step["id"]: step["status"] for step in detail["steps"]}
    assert statuses[root["id"]] == "approved"
    assert statuses[main_next["id"]] == "approved"
    assert statuses[sibling_next["id"]] == "pending"


def test_auto_run_picks_up_step_inserted_during_run(client, monkeypatch):
    task = create_task(client)
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    first_step, second_step = detail["steps"]
    executed = []
    inserted_step_id = None

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        nonlocal inserted_step_id
        executed.append(step_model.id)
        if step_model.id == first_step["id"]:
            response = client.post(
                f"/tasks/{task['id']}/steps",
                json={"title": "Inserted while running", "objective": "Run me too", "insert_mode": "insert_after_step", "target_step_id": second_step["id"]},
            )
            assert response.status_code == 200, response.text
            inserted_step_id = response.json()["id"]
        return {"summary": f"completed {step_model.id}"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(f"/tasks/{task['id']}/auto-run", json={"executor_type": "agent", "input": {}})

    assert response.status_code == 200, response.text
    assert inserted_step_id is not None
    assert executed == [first_step["id"], second_step["id"], inserted_step_id]
    detail = client.get(f"/tasks/{task['id']}").json()
    statuses = {step["id"]: step["status"] for step in detail["steps"]}
    assert statuses[inserted_step_id] == "approved"


def test_scoped_auto_run_without_current_step_does_not_fall_back_to_global_next(client):
    task = create_task(client)
    detail = client.post(
        f"/tasks/{task['id']}/generate-plan",
        json={
            "steps": [
                {"title": "Scoped first", "objective": "First"},
                {"title": "Scoped terminal", "objective": "Terminal"},
                {"title": "Unrelated pending", "objective": "Pending"},
            ]
        },
    ).json()
    approve_plan(client, task["id"])
    first_step, terminal_step, unrelated_step = detail["steps"]
    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        first_model = db.get(models.Step, first_step["id"])
        terminal_model = db.get(models.Step, terminal_step["id"])
        unrelated_model = db.get(models.Step, unrelated_step["id"])
        first_model.status = "approved"
        terminal_model.status = "approved"
        task_service.unlink_steps(terminal_model, unrelated_model)
        db.commit()
    finally:
        db.close()

    resumed = step_execution_service.execute_next_auto_run_step(
        task["id"],
        executor_type="agent",
        run_input={"instruction": "", "auto_run": True, "auto_run_start_step_id": first_step["id"]},
        current_step_id=None,
    )

    assert resumed is False
    assert client.get(f"/tasks/{task['id']}/steps/{unrelated_step['id']}/runs").json() == []


def test_auto_run_stops_without_falling_back_to_unlinked_steps(client, monkeypatch):
    task = create_task(client)
    detail = client.post(
        f"/tasks/{task['id']}/generate-plan",
        json={
            "steps": [
                {"title": "Scoped first", "objective": "First"},
                {"title": "Scoped second", "objective": "Second"},
                {"title": "Unscoped third", "objective": "Third"},
            ]
        },
    ).json()
    approve_plan(client, task["id"])
    first_step, second_step, third_step = detail["steps"]
    db_generator = client.app.dependency_overrides[get_db]()
    db = next(db_generator)
    try:
        second_model = db.get(models.Step, second_step["id"])
        third_model = db.get(models.Step, third_step["id"])
        task_service.unlink_steps(second_model, third_model)
        db.commit()
    finally:
        db.close()
    executed = []

    def fake_execute_step(task_model, step_model, run_input, previous_steps):
        executed.append(step_model.id)
        assert "auto_run_step_ids" not in run_input
        return {"summary": f"completed {step_model.id}"}

    monkeypatch.setattr(step_execution_service, "execute_step", fake_execute_step)
    response = client.post(
        f"/tasks/{task['id']}/auto-run",
        json={"executor_type": "agent", "input": {}},
    )

    assert response.status_code == 200, response.text
    assert executed == [first_step["id"], second_step["id"]]
    detail = client.get(f"/tasks/{task['id']}").json()
    statuses = {step["id"]: step["status"] for step in detail["steps"]}
    assert statuses[first_step["id"]] == "approved"
    assert statuses[second_step["id"]] == "approved"
    assert statuses[third_step["id"]] == "pending"
    assert detail["current_pointer"]["step_id"] == third_step["id"]



def test_codex_callback_retries_incomplete_result(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(codex_execution_service.settings, "codex_max_attempts", 2)
    monkeypatch.setattr(
        codex_execution_service,
        "start_task_codex_keepalive",
        lambda task_id, project_path: codex_execution_service.initialize_task_codex_session(task_id, project_path),
    )
    monkeypatch.setattr(codex_execution_service.subprocess, "run", lambda args, check: type("Result", (), {"returncode": 1 if args[:3] == ["tmux", "has-session", "-t"] else 0})())
    task_response = client.post("/tasks", json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)})
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]

    run = create_run(client, task["id"], step["id"], "agent")
    token = codex_execution_service.make_callback_token(task["id"], step["id"], run["id"], run["attempt_number"])
    response = client.post(
        f"/internal/codex/runs/{run['id']}/callback",
        headers={"Authorization": f"Bearer {token}"},
        json={
            "task_id": task["id"],
            "step_id": step["id"],
            "run_id": run["id"],
            "attempt_number": run["attempt_number"],
            "status": "failed",
            "error": "missing output",
        },
    )
    assert response.status_code == 200, response.text
    assert response.json()["retry"] is True

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert [item["status"] for item in runs] == ["rejected", "running"]
    assert [item["attempt_number"] for item in runs] == [1, 2]

    detail = client.get(f"/tasks/{task['id']}").json()
    steps = detail["steps"]
    assert len(steps) == 2
    retried_step = next(item for item in steps if item["id"] == step["id"])
    assert retried_step["comparison_group_id"] is None
    assert retried_step["is_fork"] is False
    timeline = client.get(f"/tasks/{task['id']}/timeline").json()
    event_types = [event["event_type"] for event in timeline]
    assert "step_rerun_created" in event_types
    assert "step_rerun_branch_created" not in event_types
    assert "step_branch_cloned" not in event_types



def test_codex_task_hook_completes_current_running_run(client, monkeypatch, tmp_path):
    monkeypatch.setattr(codex_execution_service.settings, "codex_enabled", True)
    monkeypatch.setattr(codex_execution_service.settings, "codex_callback_secret", "secret")
    monkeypatch.setattr(
        codex_execution_service,
        "start_task_codex_keepalive",
        lambda task_id, project_path: codex_execution_service.initialize_task_codex_session(task_id, project_path),
    )
    monkeypatch.setattr(
        codex_execution_service.subprocess,
        "run",
        lambda args, check: type("Result", (), {"returncode": 1 if args[:3] == ["tmux", "has-session", "-t"] else 0})(),
    )
    task_response = client.post("/tasks", json={"title": "Codex task", "goal": "Use Codex", "executor_mode": "codex", "project_path": str(tmp_path)})
    assert task_response.status_code == 200, task_response.text
    task = task_response.json()
    detail = generate_plan(client, task["id"])
    approve_plan(client, task["id"])
    step = detail["steps"][0]
    create_run(client, task["id"], step["id"], "agent")

    token = codex_execution_service.make_task_callback_token(task["id"])
    response = client.post(
        f"/internal/codex/tasks/{task['id']}/hook",
        headers={"Authorization": f"Bearer {token}"},
        json={"task_id": task["id"], "status": "completed", "summary": "Changed files and completed the step"},
    )
    assert response.status_code == 200, response.text
    assert response.json()["accepted"] is True

    runs = client.get(f"/tasks/{task['id']}/steps/{step['id']}/runs").json()
    assert runs[0]["status"] == "accepted"
